export const CURRENT_WEATHER_REQUESTED = 'CURRENT_WEATHER_REQUESTED'
export const CURRENT_WEATHER_SUCCEED = 'CURRENT_WEATHER_SUCCEED'
export const CURRENT_WEATHER_FAILED = 'CURRENT_WEATHER_FAILED'

export const FILTER_CITIES_REQUESTED = 'FILTER_CITIES_REQUESTED'
export const FILTER_CITIES_SUCCEED = 'FILTER_CITIES_SUCCEED'
export const FILTER_CITIES_FAILED = 'FILTER_CITIES_FAILED'
